 stages:
   - test

 html-checker:
   stage: test
   before_script:
   - bash
   - >
    if [[ $(find . -type f -name '*.html' | wc -l) -eq 0 ]]; then
        exit 0
    fi
   - apt-get update
   - apt-get -qq -y install nodejs-legacy npm curl
   - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
   - npm -qq -y install -g htmlhint
   - export NVM_DIR="${HOME}/.nvm" 
   - \. "$NVM_DIR/nvm.sh"    
   - nvm install node
   script:
   - htmlhint .

 css-checker:  
   stage: test
   before_script:
   - bash
   - >
    if [[ $(find . -type f -name '*.css' | wc -l) -eq 0 ]]; then
        exit 0
    fi
   - apt-get update
   - apt-get -qq -y install nodejs-legacy npm
   - npm -qq -y install -g csslint
   script:
   - csslint .
   
 js-checker:  
   stage: test
   before_script:
   - bash
   - >
    if [[ $(find . -type f -name '*.js' | wc -l) -eq 0 ]]; then
        exit 0
    fi
   - apt-get update
   - apt-get -qq -y install nodejs-legacy npm
   - npm -qq -y install -g jshint
   script:
   - jshint .
